import type { Property } from '@/types'

export const PROPERTIES: Property[] = [
  {
    id: '1',
    slug: 'property-1',
    title: 'Luxury Beachfront Villa with Private Pool',
    type: 'Villa',
    badge: 'Beachfront',
    badgeColor: 'gold',
    price: '₹4.8 Cr',
    location: 'Candolim, North Goa',
    beds: 4,
    baths: 4,
    area: '4200 sq.ft',
    listing: 'sale',
    region: 'north',
    sellerType: 'Verified Builder',
    img: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=700&q=80',
    featured: true,
    yearBuilt: 2019,
    garages: 2,
    propertyStatus: 'For Sale',
    description: 'Experience the pinnacle of Goan luxury in this stunning beachfront villa nestled along the pristine shores of Candolim. Designed with contemporary elegance and Goan charm, the villa features an expansive private pool, sun deck, and unobstructed sea views from every room. The interiors blend natural stone, tropical hardwoods, and bespoke furniture to create a resort-like ambiance.\n\nPerfect for high-end holiday rentals, a second home, or a lifestyle investment, this property represents an exceptional opportunity in one of Goa\'s most sought-after coastal stretches. All title documents are clear and verified.',
    features: {
      facilitiesAndConvenience: ['Private Pool', 'Beach Access', 'Landscaped Garden', 'Covered Parking', 'Gym', 'Barbeque Area'],
      interiorFeatures: ['Air Conditioning', 'Fully Furnished', 'Modular Kitchen', 'Italian Marble Flooring', 'Jacuzzi', 'Walk-in Wardrobe'],
      technologyAndEfficiency: ['Solar Panels', 'Smart Home System', 'CCTV Security', 'WiFi Ready', 'Video Door Phone'],
    },
  },
  {
    id: '2',
    slug: 'property-2',
    title: 'Premium Portuguese Style Heritage Home',
    type: 'Villa',
    badge: 'Heritage',
    badgeColor: 'navy',
    price: '₹3.2 Cr',
    location: 'Assagao, North Goa',
    beds: 3,
    baths: 3,
    area: '2800 sq.ft',
    listing: 'sale',
    region: 'north',
    sellerType: 'Owner',
    img: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=700&q=80',
    featured: true,
    yearBuilt: 1962,
    garages: 1,
    propertyStatus: 'For Sale',
    description: 'A rare gem in the heart of Assagao, this classic Portuguese heritage home has been lovingly restored to blend its original colonial character with modern comforts. High ornate ceilings, original oxide flooring, carved wooden furniture, and azulejo tile accents preserve the soul of old Goa.\n\nThe property sits on a generous plot with a private courtyard and mature fruit trees. Assagao is one of North Goa\'s most fashionable villages, surrounded by boutique cafés, art galleries, and yoga retreats — making this an ideal lifestyle purchase or premium holiday rental.',
    features: {
      facilitiesAndConvenience: ['Private Courtyard', 'Fruit Orchard', 'Covered Veranda', 'Parking', 'Storage Room'],
      interiorFeatures: ['Restored Oxide Flooring', 'Ornate Wooden Ceilings', 'Antique Furniture', 'Air Conditioning', 'Modular Kitchen'],
      technologyAndEfficiency: ['Security System', 'WiFi Ready', 'Energy Efficient Lighting', 'Rainwater Harvesting'],
    },
  },
  {
    id: '3',
    slug: 'property-3',
    title: 'Modern Sea View Apartment',
    type: 'Apartment',
    badge: 'Sea View',
    price: '₹1.8 Cr',
    location: 'Dona Paula, Goa',
    beds: 3,
    baths: 2,
    area: '1900 sq.ft',
    listing: 'sale',
    region: 'north',
    sellerType: 'Verified Agent',
    img: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=700&q=80',
    featured: true,
    yearBuilt: 2021,
    garages: 1,
    propertyStatus: 'For Sale',
    description: 'Wake up to breathtaking panoramic views of the Arabian Sea from this premium 3BHK apartment in Dona Paula. Located on a high floor in a well-maintained gated complex, the apartment offers a contemporary open-plan layout with floor-to-ceiling windows that flood every room with natural light and sea breeze.\n\nThe complex features a rooftop infinity pool, clubhouse, and 24-hour security. Just minutes from Miramar Beach, the Dona Paula jetty, and Panaji city centre, this is an ideal blend of coastal lifestyle and urban convenience.',
    features: {
      facilitiesAndConvenience: ['Rooftop Infinity Pool', 'Clubhouse', 'Covered Parking', 'Lift', 'Children\'s Play Area'],
      interiorFeatures: ['Air Conditioning', 'Semi-Furnished', 'Vitrified Tile Flooring', 'Modular Kitchen', 'Compact Kitchen'],
      technologyAndEfficiency: ['CCTV Security', 'Video Door Phone', 'WiFi Ready', 'Power Backup', 'Smart Meters'],
    },
  },
  {
    id: '4',
    slug: 'property-4',
    title: 'Luxury Villa Near Baga Beach',
    type: 'Villa',
    badge: 'Prime Location',
    badgeColor: 'gold',
    price: '₹5.5 Cr',
    location: 'Baga, North Goa',
    beds: 5,
    baths: 5,
    area: '5000 sq.ft',
    listing: 'sale',
    region: 'north',
    sellerType: 'Builder',
    img: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=700&q=80',
    featured: true,
    yearBuilt: 2020,
    garages: 2,
    propertyStatus: 'For Sale',
    description: 'An imposing luxury villa located just a short walk from the vibrant shores of Baga Beach. Spanning 5,000 sq.ft across three levels, this five-bedroom villa is designed for large families or premium hospitality use. The property features a temperature-controlled pool, rooftop terrace with Jacuzzi, and a spacious landscaped garden ideal for entertaining.\n\nWith top-of-the-line finishes — Italian marble, designer fixtures, and a fully-equipped gourmet kitchen — this villa sets a new benchmark in Goa\'s luxury residential segment. Strong rental yields make it an attractive investment.',
    features: {
      facilitiesAndConvenience: ['Private Pool', 'Rooftop Jacuzzi', 'Landscaped Garden', 'Double Garage', 'Staff Quarters', 'Gym'],
      interiorFeatures: ['Italian Marble Flooring', 'Fully Furnished', 'Gourmet Kitchen', 'Home Theatre', 'Air Conditioning', 'Walk-in Wardrobe'],
      technologyAndEfficiency: ['Smart Home System', 'Solar Power', 'CCTV Security', 'WiFi Ready', 'Automated Lighting', 'Energy Efficient Lighting'],
    },
  },
  {
    id: '5',
    slug: 'property-5',
    title: 'Residential Plot Near Beach',
    type: 'Plot',
    badge: 'Investment',
    price: '₹95 Lakhs',
    location: 'Morjim, North Goa',
    beds: null,
    baths: null,
    area: '2400 sq.ft',
    listing: 'sale',
    region: 'north',
    sellerType: 'Agent',
    img: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=700&q=80',
    featured: true,
    yearBuilt: undefined,
    garages: undefined,
    propertyStatus: 'For Sale',
    description: 'A well-positioned residential plot just minutes from the serene turtle beach at Morjim. The plot comes with clear titles and all approvals in place, making it immediately ready for construction. Morjim is one of the last pristine stretches of North Goa\'s coastline, attracting premium villa developments and upscale retreats.\n\nThis is an exceptional land banking opportunity — ideal for building a private villa, holiday home, or a boutique resort. Surrounded by lush greenery with access to the beach road, connectivity is excellent.',
    features: {
      facilitiesAndConvenience: ['Clear Title', 'Road Access', 'Near Beach', 'Electricity Connection Available', 'Water Connection Available'],
      interiorFeatures: [],
      technologyAndEfficiency: ['Approved Layout', 'Panchayat NOC'],
    },
  },
  {
    id: '6',
    slug: 'property-6',
    title: 'Boutique Resort Investment Property',
    type: 'Commercial',
    badge: 'High Returns',
    badgeColor: 'gold',
    price: '₹6.2 Cr',
    location: 'Anjuna, Goa',
    beds: null,
    baths: null,
    area: '6500 sq.ft',
    listing: 'sale',
    region: 'north',
    sellerType: 'Developer',
    img: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=700&q=80',
    featured: true,
    yearBuilt: 2017,
    garages: 3,
    propertyStatus: 'For Sale',
    description: 'An established boutique resort in the heart of Anjuna, currently operating with strong occupancy rates and consistent rental income. The property comprises 12 well-appointed cottages, a central pool, an open-air restaurant, and a yoga pavilion set within lush tropical gardens.\n\nAnjuna is one of Goa\'s most popular tourist destinations with an active flea market, vibrant nightlife, and a loyal international visitor base. This is a rare opportunity to acquire a fully operational hospitality asset with immediate revenue generation and significant appreciation potential.',
    features: {
      facilitiesAndConvenience: ['Swimming Pool', 'Open-Air Restaurant', 'Yoga Pavilion', 'Ample Parking', 'Reception Area', 'Garden'],
      interiorFeatures: ['Air Conditioning in All Units', 'Fully Furnished Rooms', 'Attached Bathrooms', 'Hot Water'],
      technologyAndEfficiency: ['CCTV Security', 'WiFi Throughout', 'Solar Water Heating', 'Power Backup', 'Fire Safety System'],
    },
  },
  {
    id: '7',
    slug: 'property-7',
    title: '2BHK Apartment in Bambolim',
    type: 'Apartment',
    badge: 'Hot',
    badgeColor: 'gold',
    price: '₹2.32 Cr',
    location: 'Bambolim, North Goa',
    beds: 2,
    baths: 2,
    area: '1550 sq.ft',
    listing: 'sale',
    region: 'north',
    sellerType: 'Agent',
    img: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=700&q=80',
    yearBuilt: 2022,
    garages: 1,
    propertyStatus: 'For Sale',
    description: 'A modern 2BHK apartment in the rapidly growing Bambolim township, home to Goa\'s premier hospitals, educational institutions, and the upcoming IT park. Well-planned layout with a spacious living area, large balcony with garden views, and premium fittings throughout.\n\nBambolim offers the perfect balance of urban convenience and Goan tranquility, with easy access to Panaji (8 km) and Vasco (12 km). An excellent choice for end-users and investors alike.',
    features: {
      facilitiesAndConvenience: ['Swimming Pool', 'Clubhouse', 'Children\'s Play Area', 'Covered Parking', 'Lift'],
      interiorFeatures: ['Air Conditioning', 'Vitrified Flooring', 'Modular Kitchen', 'Large Balcony', 'Wardrobes'],
      technologyAndEfficiency: ['CCTV Security', 'Video Intercom', 'Power Backup', 'WiFi Ready'],
    },
  },
  {
    id: '8',
    slug: 'property-8',
    title: '3BHK Villa for Rent in Siolim',
    type: 'Villa',
    badge: '',
    price: '₹55,000',
    priceNote: '/month',
    location: 'Siolim, North Goa',
    beds: 3,
    baths: 3,
    area: '2800 sq.ft',
    listing: 'rent',
    region: 'north',
    sellerType: 'Owner',
    img: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=700&q=80',
    yearBuilt: 2016,
    garages: 1,
    propertyStatus: 'For Rent',
    description: 'A beautifully maintained 3BHK villa in the peaceful village of Siolim, available for long-term rental. The villa features a private garden, covered parking, and a large living-dining area with high ceilings. Each bedroom has an attached bathroom and direct garden access.\n\nSiolim is ideally located between the beaches of Anjuna, Vagator, and Morjim, offering the best of North Goa\'s lifestyle. Nearby are organic cafés, spas, and yoga studios. Available for a minimum lease of 11 months.',
    features: {
      facilitiesAndConvenience: ['Private Garden', 'Covered Parking', 'Veranda', 'Storage Room'],
      interiorFeatures: ['Air Conditioning', 'Semi-Furnished', 'Tiled Flooring', 'Modular Kitchen', 'Window Coverings'],
      technologyAndEfficiency: ['Security System', 'WiFi Ready', 'Energy Efficient Lighting'],
    },
  },
  {
    id: '9',
    slug: 'property-9',
    title: 'Furnished Apartment in Panjim',
    type: 'Apartment',
    badge: '',
    price: '₹22,000',
    priceNote: '/month',
    location: 'Panjim, Goa',
    beds: 2,
    baths: 2,
    area: '1100 sq.ft',
    listing: 'rent',
    region: 'north',
    sellerType: 'Owner',
    img: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=700&q=80',
    yearBuilt: 2018,
    garages: 1,
    propertyStatus: 'For Rent',
    description: 'A fully furnished 2BHK apartment in the heart of Panjim, Goa\'s bustling capital city. The apartment is move-in ready with quality furniture, a fully equipped kitchen, and all essential appliances. Located in a well-maintained building with lift access and covered parking.\n\nPanjim offers excellent connectivity, proximity to government offices, banks, restaurants, and entertainment. The Mandovi River promenade and heritage Fontainhas precinct are within walking distance. Ideal for professionals and families.',
    features: {
      facilitiesAndConvenience: ['Lift', 'Covered Parking', 'Security Guard', 'Common Area Maintenance'],
      interiorFeatures: ['Fully Furnished', 'Air Conditioning', 'Refrigerator', 'Washing Machine', 'Compact Kitchen', 'Microwave', 'Work Desk'],
      technologyAndEfficiency: ['CCTV in Common Areas', 'WiFi Ready', 'Power Backup'],
    },
  },
  {
    id: '10',
    slug: 'property-10',
    title: 'Plot for Sale in Porvorim',
    type: 'Plot',
    badge: '',
    price: '₹1.1 Cr',
    location: 'Porvorim, North Goa',
    beds: null,
    baths: null,
    area: '3200 sq.ft',
    listing: 'sale',
    region: 'north',
    sellerType: 'Agent',
    img: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=700&q=80',
    yearBuilt: undefined,
    garages: undefined,
    propertyStatus: 'For Sale',
    description: 'A prime residential plot situated in the fast-developing suburb of Porvorim, one of Goa\'s most sought-after addresses due to its proximity to Panaji (5 km) and key commercial corridors. The plot enjoys excellent road connectivity, clear legal title, and all municipal approvals.\n\nPortovorim is home to premier schools, hospitals, banks, and shopping centres, making it ideal for building a family home. The relatively flat terrain and rectangular shape make construction straightforward.',
    features: {
      facilitiesAndConvenience: ['Clear Title', 'Road Access', 'Electricity Available', 'Water Connection Available', 'Near Schools & Hospitals'],
      interiorFeatures: [],
      technologyAndEfficiency: ['Approved Layout', 'Corporation NOC'],
    },
  },
]

export const LOCATIONS = [
  'All Goa', 'Anjuna', 'Arpora', 'Ashwem', 'Assagao', 'Baga', 'Bambolim',
  'Calangute', 'Candolim', 'Chapora', 'Colva', 'Dona Paula', 'Mandrem',
  'Mapusa', 'Margao', 'Morjim', 'Panjim', 'Porvorim', 'Siolim',
  'Vagator', 'Vasco', 'Aldona', 'Benaulim', 'Betalbatim', 'Cavelossim',
  'Bogmalo', 'Curchorem', 'Palolem', 'Agonda',
]

export const PROPERTY_TYPES = [
  { label: 'All Types', value: '' },
  { label: 'Apartments & Penthouses', value: 'apartments' },
  { label: 'Bungalows & Villas', value: 'villas' },
  { label: 'Portuguese Houses', value: 'portuguese' },
  { label: 'Plots', value: 'plots' },
  { label: 'Boutique Resort', value: 'resort' },
  { label: 'Beach / River Side Properties', value: 'beach' },
  { label: 'Agriculture / Farm Land', value: 'farm' },
  { label: 'Row House & Duplex', value: 'rowhouse' },
  { label: 'Industrial Sheds / Plots', value: 'industrial' },
  { label: 'Commercial', value: 'commercial' },
]

export const BUDGET_OPTIONS = [
  { label: 'Any Budget', value: '' },
  { label: 'Under ₹50 Lakhs', value: '0-50' },
  { label: '₹50L – ₹1 Cr', value: '50-100' },
  { label: '₹1 Cr – ₹2 Cr', value: '100-200' },
  { label: '₹2 Cr – ₹5 Cr', value: '200-500' },
  { label: 'Above ₹5 Cr', value: '500+' },
]

export const RENT_BUDGET_OPTIONS = [
  { label: 'Any Budget', value: '' },
  { label: 'Under ₹10k/mo', value: '0-10' },
  { label: '₹10k – ₹25k/mo', value: '10-25' },
  { label: '₹25k – ₹50k/mo', value: '25-50' },
  { label: '₹50k – ₹1L/mo', value: '50-100' },
  { label: 'Above ₹1L/mo', value: '100+' },
]

export const GOA_PLACES = [
  // North Goa areas
  'Anjuna', 'Arambol', 'Arpora', 'Ashwem', 'Assagao', 'Baga', 'Bambolim', 'Bicholim',
  'Calangute', 'Candolim', 'Caranzalem', 'Chapora', 'Chicalim', 'Dona Paula',
  'Fontainhas', 'Mandrem', 'Mapusa', 'Miramar', 'Moira', 'Morjim',
  'Nachinola', 'Nerul', 'Old Goa', 'Panjim', 'Panaji', 'Pernem',
  'Pilerne', 'Ponda', 'Porvorim', 'Reis Magos', 'Ribandar',
  'Saligao', 'Sangolda', 'Siolim', 'Sinquerim', 'Socorro', 'Tivim', 'Vagator',
  // South Goa areas
  'Agonda', 'Benaulim', 'Betalbatim', 'Bogmalo', 'Canacona', 'Cavelossim',
  'Colva', 'Cortalim', 'Curchorem', 'Dabolim', 'Goa Velha', 'Loutolim',
  'Majorda', 'Margao', 'Nuvem', 'Palolem', 'Quepem',
  'Sanguem', 'Utorda', 'Vasco', 'Verna',
  // Regions
  'North Goa', 'South Goa', 'All Goa',
  // Beaches
  'Agonda Beach', 'Anjuna Beach', 'Arambol Beach', 'Ashwem Beach',
  'Baga Beach', 'Benaulim Beach', 'Bogmalo Beach', 'Calangute Beach',
  'Candolim Beach', 'Cavelossim Beach', 'Colva Beach', 'Dona Paula Beach',
  'Mandrem Beach', 'Miramar Beach', 'Morjim Beach', 'Palolem Beach',
  'Sinquerim Beach', 'Vagator Beach',
  // Notable localities
  'Aldona', 'Altinho', 'Cansaulim', 'Corjuem', 'Mapusa Market',
  'Panjim City', 'Raia', 'Soccoro',
]

export const FEATURED_PROPERTIES = PROPERTIES.filter((p) => p.featured)
export const SALE_PROPERTIES = PROPERTIES.filter((p) => p.listing === 'sale')
export const RENT_PROPERTIES = PROPERTIES.filter((p) => p.listing === 'rent')
