-- Master locations picklist for the Property Location field. Seeded with
-- the exact villages that were previously hardcoded in the CRM's Add
-- Property form, so switching that form over to read from this table is a
-- no-op for existing data — new entries added via "Add Location +" simply
-- insert here going forward.

CREATE TABLE "locations" (
  "id"         TEXT NOT NULL,
  "village"    TEXT NOT NULL,
  "taluka"     "GoaTaluka" NOT NULL,
  "region"     "GoaRegion" NOT NULL,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "locations_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "locations_village_key" ON "locations"("village");
CREATE INDEX "locations_region_taluka_idx" ON "locations"("region", "taluka");

INSERT INTO "locations" ("id", "village", "taluka", "region") VALUES
  (gen_random_uuid()::text, 'Aldona', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Altinho', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Anjuna', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Aquem', 'SALCETE', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Arpora', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Ashwem', 'PERNEM', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Assagao', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Badem', 'BICHOLIM', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Bainguinim', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Baga', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Bambolim', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Banastarim', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Bastora', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Benaulim', 'SALCETE', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Betalbatim', 'SALCETE', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Betim', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Betul', 'SALCETE', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Bhatlem', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Bicholim', 'BICHOLIM', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Bogmalo', 'MORMUGAO', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Calangute', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Campal', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Canacona', 'CANACONA', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Candolim', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Caranzalem', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Carmona', 'SALCETE', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Cavelossim', 'SALCETE', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Chapora', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Chicalim', 'MORMUGAO', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Chimbel', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Chorao', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Colva', 'SALCETE', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Colvale', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Corlim', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Corgao', 'PERNEM', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Cortalim', 'MORMUGAO', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Curca', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Curchorem', 'QUEPEM', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Dabolim', 'MORMUGAO', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Diwar', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Dona Paula', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Duler', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Goa Velha', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Gogol', 'SALCETE', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Guirim', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Kadamba Plateau', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Kerim', 'PERNEM', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Loutolim', 'SALCETE', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Mandrem', 'PERNEM', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Mapusa', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Marcela', 'PONDA', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Margao', 'SALCETE', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Merces', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Miramar', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Moira', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Mopa', 'PERNEM', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Morjim', 'PERNEM', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Nachinola', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Nagoa', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Navelim', 'SALCETE', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Nerul', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'North Goa', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Old Goa', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Oxel', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Panjim', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Parra', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Pernem', 'PERNEM', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Pilar', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Pilerne', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Ponda', 'PONDA', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Porvorim', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Porvorim Succour', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Raibander', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Reis Magos', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Saligao', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Salvador do Mundo', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Sangolda', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Siolim', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'South Goa', 'SALCETE', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'St. Cruz', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'St. Inez', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Succour', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Taleigao', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Tambdi Surla', 'SANGUEM', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Tivim', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Tonca', 'TISWADI', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Uccassaim', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Valpoi', 'BICHOLIM', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Varca', 'SALCETE', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Vasco', 'MORMUGAO', 'SOUTH_GOA'),
  (gen_random_uuid()::text, 'Vagator', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Verem', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Verla', 'BARDEZ', 'NORTH_GOA'),
  (gen_random_uuid()::text, 'Verna', 'SALCETE', 'SOUTH_GOA')
ON CONFLICT ("village") DO NOTHING;
